import { Component, inject, signal, OnInit, OnDestroy, ElementRef, viewChild, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CatalogService } from '../../../../core/services/catalog.service';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
import { Order } from '../../../../core/models';
import { ButtonComponent } from '../../../../shared/ui/button/button.component';
import { BrowserQRCodeReader } from '@zxing/browser';

@Component({
  selector: 'app-validar-retiro',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, ButtonComponent],
  template: `
    <div class="space-y-5 pb-8 max-w-lg mx-auto">
      <!-- Top Nav -->
      <a
        routerLink="/comercio"
        class="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 transition"
      >
        <svg class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
        </svg>
        <span>Volver a bandeja de pedidos</span>
      </a>

      <!-- Header -->
      <div class="space-y-1">
        <h1 class="text-xl font-black tracking-tight text-slate-900">Validar Retiro con QR</h1>
        <p class="text-xs text-slate-500">
          Escanea el código QR del cliente con la cámara o introduce su PIN de 4 dígitos.
        </p>
      </div>

      <!-- SUCCESS CONFIRMATION MODAL / CARD -->
      @if (validatedResult()) {
        <div class="bg-white rounded-3xl border-2 border-emerald-500 p-6 shadow-lg text-center space-y-4 animate-in fade-in zoom-in duration-200">
          <div class="size-16 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mx-auto text-2xl">
            ✓
          </div>

          <div class="space-y-1">
            <span class="text-xs font-bold uppercase tracking-wider text-emerald-600">¡Retiro Validado!</span>
            <h2 class="text-lg font-black text-slate-900">Pedido Entregado con Éxito</h2>
            <p class="text-xs text-slate-500">
              El inventario se ha actualizado y el pedido ha pasado a estado <strong>entregado</strong>.
            </p>
          </div>

          <!-- Parking Validation Banner Generated by RPC -->
          <div class="p-4 bg-emerald-950 text-emerald-200 rounded-2xl text-left space-y-2 border border-emerald-700/50">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2">
                <span class="text-xl">🚗</span>
                <span class="text-xs font-bold text-white">Ticket de Parqueo Activado</span>
              </div>
              <span class="px-2 py-0.5 rounded bg-emerald-800 text-[10px] font-bold text-emerald-100">
                2 Hrs Libres
              </span>
            </div>
            <p class="text-[11px] text-emerald-300 leading-snug">
              {{ validatedResult().parking?.mensaje || 'Se ha generado la validación de salida sin costo en el parqueo subterráneo de Paseo Aranjuez.' }}
            </p>
            <div class="pt-1 text-[11px] font-mono text-emerald-400">
              CÓDIGO: {{ validatedResult().parking?.codigo_qr || 'PARK-VALID' }}
            </div>
          </div>

          <div class="pt-2 flex flex-col gap-2">
            <app-button
              variant="primary"
              [fullWidth]="true"
              (clicked)="resetScanner()"
            >
              Validar Siguiente Pedido
            </app-button>
            <a
              routerLink="/comercio"
              class="text-xs font-bold text-slate-600 hover:text-slate-900 py-1"
            >
              Ir a la bandeja de pedidos
            </a>
          </div>
        </div>
      } @else {
        <!-- SCANNER SECTION -->
        <div class="bg-white rounded-3xl border border-slate-200/90 overflow-hidden shadow-2xs">
          <!-- Camera Viewfinder -->
          <div class="relative bg-slate-950 aspect-4/3 flex items-center justify-center overflow-hidden">
            <video
              #videoElement
              class="w-full h-full object-cover"
              [class.hidden]="!cameraActive()"
            ></video>

            @if (!cameraActive()) {
              <div class="text-center p-6 space-y-3">
                <div class="size-14 rounded-2xl bg-slate-800 text-slate-300 flex items-center justify-center mx-auto text-2xl">
                  📷
                </div>
                <div>
                  <p class="text-xs font-bold text-slate-200">Cámara Inactiva</p>
                  <p class="text-[11px] text-slate-400 mt-0.5">Presiona el botón para escanear el QR del cliente</p>
                </div>
                <button
                  type="button"
                  (click)="startScanner()"
                  class="h-10 px-4 bg-emerald-600 hover:bg-emerald-500 active:scale-95 text-white text-xs font-bold rounded-xl transition cursor-pointer"
                >
                  Activar Cámara
                </button>
              </div>
            } @else {
              <!-- Scanner Reticle overlay -->
              <div class="absolute inset-0 border-40 border-black/50 flex items-center justify-center pointer-events-none">
                <div class="size-48 border-2 border-amber-400 rounded-2xl relative shadow-lg">
                  <div class="absolute -top-1 -left-1 size-4 border-t-4 border-l-4 border-amber-400 rounded-tl"></div>
                  <div class="absolute -top-1 -right-1 size-4 border-t-4 border-r-4 border-amber-400 rounded-tr"></div>
                  <div class="absolute -bottom-1 -left-1 size-4 border-b-4 border-l-4 border-amber-400 rounded-bl"></div>
                  <div class="absolute -bottom-1 -right-1 size-4 border-b-4 border-r-4 border-amber-400 rounded-br"></div>
                  <div class="h-0.5 w-full bg-amber-400 animate-pulse mt-24 opacity-80"></div>
                </div>
              </div>

              <!-- Stop Camera Button -->
              <button
                type="button"
                (click)="stopScanner()"
                class="absolute top-3 right-3 px-2.5 py-1 rounded-lg bg-black/60 text-white text-[10px] font-bold hover:bg-black/80 transition"
              >
                Apagar cámara
              </button>
            }
          </div>

          <!-- MANUAL CODE OR PIN INPUT -->
          <div class="p-5 border-t border-slate-100 space-y-4">
            <div class="flex items-center gap-2">
              <span class="text-xs font-black uppercase tracking-wider text-slate-400">
                O ingresa el código manualmente
              </span>
              <div class="flex-1 h-px bg-slate-200"></div>
            </div>

            <!-- Target Order Selector -->
            <div>
              <label class="block text-xs font-semibold text-slate-700 mb-1" for="orderSelect">
                Selecciona Pedido Pendiente
              </label>
              <select
                id="orderSelect"
                [(ngModel)]="selectedOrderId"
                class="w-full h-11 px-3 text-xs bg-slate-50 border border-slate-300 rounded-xl focus:outline-none focus:border-slate-900 focus:bg-white"
              >
                <option value="">-- Elige un pedido para validar --</option>
                @for (o of pendingOrders(); track o.id) {
                  <option [value]="o.id">
                    {{ o.pickup_code }} &middot; {{ o.cliente?.nombre_completo || 'Cliente' }} (Bs. {{ o.total | number:'1.2-2' }})
                  </option>
                }
              </select>
            </div>

            <!-- Manual PIN or Code -->
            <div>
              <label class="block text-xs font-semibold text-slate-700 mb-1" for="manualCode">
                PIN de 4 dígitos o Código QR
              </label>
              <div class="flex gap-2">
                <input
                  id="manualCode"
                  type="text"
                  [(ngModel)]="manualCode"
                  placeholder="Ej: 4821 o PY-A89F2"
                  class="flex-1 h-11 px-3.5 text-sm font-mono font-bold uppercase bg-slate-50 border border-slate-300 rounded-xl focus:outline-none focus:border-slate-900 focus:bg-white"
                  (keyup.enter)="validateManual()"
                />
                <app-button
                  size="md"
                  [disabled]="!manualCode.trim() || !selectedOrderId"
                  [loading]="validating()"
                  (clicked)="validateManual()"
                >
                  Validar
                </app-button>
              </div>
              <p class="text-[10px] text-slate-500 mt-1">
                El cliente puede dictarte su PIN numérico mostrado en su pantalla de PaseoYa.
              </p>
            </div>
          </div>
        </div>
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ValidarRetiroComponent implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private catalogService = inject(CatalogService);
  private toastService = inject(ToastService);

  videoElement = viewChild<ElementRef<HTMLVideoElement>>('videoElement');

  cameraActive = signal<boolean>(false);
  validating = signal<boolean>(false);
  validatedResult = signal<any | null>(null);

  manualCode = '';
  selectedOrderId = '';
  pendingOrders = signal<Order[]>([]);

  private codeReader: BrowserQRCodeReader | null = null;
  private controls: any = null;

  ngOnInit(): void {
    this.refreshPendingOrders();

    this.route.queryParams.subscribe((params) => {
      if (params['orderId']) {
        this.selectedOrderId = params['orderId'];
      }
      if (params['code']) {
        this.manualCode = params['code'];
      }
    });
  }

  ngOnDestroy(): void {
    this.stopScanner();
  }

  refreshPendingOrders(): void {
    const list = this.catalogService.orders().filter(
      (o) => o.estado === 'listo_para_recoger' || o.estado === 'cliente_llego' || o.estado === 'recibido' || o.estado === 'confirmado' || o.estado === 'preparando'
    );
    this.pendingOrders.set(list);
    if (!this.selectedOrderId && list.length > 0) {
      this.selectedOrderId = list[0].id;
    }
  }

  async startScanner(): Promise<void> {
    try {
      this.codeReader = new BrowserQRCodeReader();
      const video = this.videoElement()?.nativeElement;
      if (!video) return;

      this.cameraActive.set(true);

      this.controls = await this.codeReader.decodeFromVideoDevice(
        undefined,
        video,
        (result, error) => {
          if (result) {
            this.handleScan(result.getText());
          }
        }
      );
    } catch (e: any) {
      console.warn('Error starting camera scanner:', e);
      this.toastService.error('No se pudo acceder a la cámara. Usa el ingreso por PIN.');
      this.cameraActive.set(false);
    }
  }

  stopScanner(): void {
    if (this.controls) {
      this.controls.stop();
      this.controls = null;
    }
    this.cameraActive.set(false);
  }

  handleScan(rawText: string): void {
    this.stopScanner();

    // Check if JSON payload from client order QR
    let codeToUse = rawText;
    let scannedOrderId = this.selectedOrderId;

    try {
      const parsed = JSON.parse(rawText);
      if (parsed.code) codeToUse = parsed.code;
      if (parsed.orderId) scannedOrderId = parsed.orderId;
    } catch (e) {
      // Plain text QR
    }

    this.manualCode = codeToUse;
    if (scannedOrderId) {
      this.selectedOrderId = scannedOrderId;
    }

    this.executeValidation(scannedOrderId, codeToUse);
  }

  async validateManual(): Promise<void> {
    if (!this.selectedOrderId || !this.manualCode.trim()) {
      this.toastService.error('Ingresa el código o PIN y selecciona el pedido.');
      return;
    }

    await this.executeValidation(this.selectedOrderId, this.manualCode);
  }

  private async executeValidation(orderId: string, code: string): Promise<void> {
    this.validating.set(true);

    try {
      const res = await this.catalogService.validarRetiro(orderId, code);

      if (res.success) {
        this.validatedResult.set(res);
        this.toastService.success('¡Retiro validado con éxito!');
      } else {
        this.toastService.error(res.error || 'Código inválido');
      }
    } catch (e: any) {
      this.toastService.error(e.message || 'Error al validar el retiro');
    } finally {
      this.validating.set(false);
    }
  }

  resetScanner(): void {
    this.validatedResult.set(null);
    this.manualCode = '';
    this.refreshPendingOrders();
  }
}
